name: Run

on:
  push:
    branches: ["maine"]

jobs:
  build:
    env:
      PY_COLORS: "1"
    name: Install Dependencies
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        rangeIndex: [0 5,5 10,10 15,15 20,20 25,25 30,30 35,35 40,40 45,45 50,50 55,55 60,60 65,65 70,70 75,75 80,80 85,85 90,90 95,95 100]
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install
        run: |
          python -m pip install --upgrade pip wheel setuptools
          python -m pip install selenium
          python -m pip install supabase
          sudo apt install -y google-chrome-stable
          sudo apt install -y xvfb
          export DISPLAY=:0
          /usr/bin/Xvfb :0 -screen 0 1024x768x24 &
          sleep 5
          xvfb-run python run-t.py ${{matrix.RangeIndex}}
      - name: done
        run: exit
